version: '3.9'
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: tsdb
    restart: always
    environment:
      - POSTGRES_PASSWORD=${TSDB_PASSWORD}
      - POSTGRES_USER=${TSDB_USER}
      - POSTGRES_DB=${TSDB_DBNAME}
    ports:
      - "5435:5432"
